<?php

/** 
 *  Addressbook module for drupal 
 *
 *  Copyright (C) 2006-2010
 *  =======================
 *
 *  Created by wplaat
 *
 *  For more information visit the following website.
 *  Website : http://www.plaatsoft.nl 
 *
 *  Or send an email to the following address.
 *  Email   : info@plaatsoft.nl
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, version 2.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

// ##################################################################################
// Defines
// ##################################################################################

// Module version
define('ADDRESSBOOK_VERSION' ,'4.0');

// Addressbook module URLs.
define('URL_ADDRESSBOOK',  'addressbook');
define('URL_FAMILY_LIST',  'addressbook/family/list');
define('URL_FAMILY_VIEW',  'addressbook/family/view');
define('URL_FAMILY_EDIT',  'addressbook/family/edit');
define('URL_MEMBER_LIST',  'addressbook/member/list');
define('URL_MEMBER_VIEW',  'addressbook/member/view');
define('URL_MEMBER_EDIT',  'addressbook/member/edit');
define('URL_PICTURE_VIEW', 'addressbook/picture/view');
define('URL_PICTURE_EDIT', 'addressbook/picture/edit');
define('URL_UPLOAD_CSV',   'addressbook/csv/upload');
define('URL_DOWNLOAD_CSV', 'addressbook/csv/download');
define('URL_SEARCH',       'addressbook/search');
define('URL_MAP_VIEW',     'addressbook/map/view');
define('URL_EMAIL',        'addressbook/email');

define('IMAGE_DIR',        file_directory_path().'/addressbook');
define('THUMBNAILS_DIR',   file_directory_path().'/addressbook/thumbnails');

// ##################################################################################
// Load all php, js and css files
// ##################################################################################

// PHP module files
module_load_include('inc', 'addressbook', 'addressbook_utils'); 
module_load_include('inc', 'addressbook', 'addressbook_mainmenu');
module_load_include('inc', 'addressbook', 'addressbook_family');
module_load_include('inc', 'addressbook', 'addressbook_member');
module_load_include('inc', 'addressbook', 'addressbook_utils');
module_load_include('inc', 'addressbook', 'addressbook_csv');
module_load_include('inc', 'addressbook', 'addressbook_other');

// ADD Java Scripts files
drupal_add_js(drupal_get_path('module', 'addressbook'). '/js/addressbook.js');

// Add CSS files
drupal_add_css(drupal_get_path('module', 'addressbook') .'/css/addressbook.css');

// ##################################################################################
// Help
// ##################################################################################

/**
 * help hook()
 * @return help texts
 */
function addressbook_help($path, $arg) {

  $output = '';
  switch ($path) {
    case 'admin/modules#description':
      $output .= t('Addressbook module');
      break;
  }
  return $output;
}

// ##################################################################################
// Mail
// ##################################################################################

function addressbook_mail($key, &$message, $params) 
{
  $message['subject'] = $params['subject']; 
  $message['body'] = $params['body'];
}

// ##################################################################################
// Menu
// ##################################################################################

/**
 * menu hook()
 * @return array of menu items
 */
function addressbook_menu() {

	$items[URL_ADDRESSBOOK] = array(
                   'title' => 'Addressbook main menu',
                   'page callback' => 'addressbook_mainmenu',
                   'access arguments' => array('view addressbook'),
                   'type' => MENU_CALLBACK,
                );

  $items[URL_FAMILY_LIST] = array(
                   'title' => 'Addressbook family list',
                   'page callback' => 'family_list',
                   'access arguments' => array('view addressbook'),
                   'type' => MENU_CALLBACK,
                );

  $items[URL_FAMILY_VIEW] = array(
                   'title' => 'Addressbook view family',
                   'page callback' => 'family_view2',
                   'access arguments' => array('view addressbook'),
                   'type' => MENU_CALLBACK,
                );

  $items[URL_FAMILY_EDIT] = array(
                   'title' => 'Addressbook edit family',
                   'page callback' => 'family_edit',
                   'access arguments' => array('add address'),
                   'type' => MENU_CALLBACK,
                );

  $items[URL_MEMBER_LIST] = array(
                   'title' => 'Addressbook family list',
                   'page callback' => 'member_list',
                   'access arguments' => array('view addressbook'),
                   'type' => MENU_CALLBACK,
                        );

  $items[URL_MEMBER_VIEW] = array(
                   'title' => 'Addressbook view family member',
                   'page callback' => 'member_view',
                   'access arguments' => array('view addressbook'),
                   'type' => MENU_CALLBACK,
                        );

  $items[URL_MEMBER_EDIT] = array(
                   'title' => 'Addressbook edit family member',
                   'page callback' => 'member_edit',
                   'access arguments' => array('add address'),
                   'type' => MENU_CALLBACK,
                        );

  $items[URL_PICTURE_VIEW] = array(
                   'title' => 'Addressbook view picture',
                   'page callback' => 'picture_view',
                   'access arguments' => array('view addressbook'),
                   'type' => MENU_CALLBACK,
                );

  $items[URL_PICTURE_EDIT] = array(
                   'title' => 'Addressbook edit picture',
                   'page callback' => 'picture_edit',
                   'access arguments' => array('add address'),
                   'type' => MENU_CALLBACK,
                        );

  $items[URL_UPLOAD_CSV] = array(
                   'title' => 'Addressbook CSV upload',
                   'page callback' => 'upload_csv',
                   'access arguments' => array('add address'),
                   'type' => MENU_CALLBACK,
                );

  $items[URL_DOWNLOAD_CSV] = array(
                   'title' => 'Addressbook CSV download',
                   'page callback' => 'download_csv',
                   'access arguments' => array('add address'),
                   'type' => MENU_CALLBACK,
                );

   $items[URL_SEARCH] = array(
                   'title' => 'Addressbook search',
                   'page callback' => 'general_search',
                   'access arguments' => array('view addressbook'),
                   'type' => MENU_CALLBACK,
                );

   $items[URL_MAP_VIEW] = array(
                   'title' => 'Addressbook map view',
                   'page callback' => 'map_view',
                   'access arguments' => array('view addressbook'),
                   'type' => MENU_CALLBACK,
                );

   $items[URL_EMAIL] = array(
                   'title' => 'Addressbook email view',
                   'page callback' => 'email_view',
                   'access arguments' => array('add address'),
                   'type' => MENU_CALLBACK,
                );

   $items['admin/settings/addressbook'] = array(
                   'title' => 'Addressbook',
                   'description' => 'Settings of addressbook.',
                   'page callback' => 'drupal_get_form',
                   'page arguments' => array('addressbook_settings'),
                   'access arguments' => array('administer site configuration'),
                   'type' => MENU_NORMAL_ITEM,
                );

  return $items;
}

// ##################################################################################
// Permission
// ##################################################################################

/**
  * Valid permissions for this module.
  * @return array an array of valid permission for the module
  */
function addressbook_perm() {

  return array('view addressbook','add address');
}

// ##################################################################################
// Settings page
// ##################################################################################

/**
 * Module configuration settings.
 * @return settings HTML or deny access
 */
function addressbook_settings() {

  //only administrators can access this module
  if (!user_access('access administration pages')) {
    return drupal_access_denied();
  }

  $form['settings_general'] = array('#type' => 'fieldset', '#title' => t('General settings'));

  $form['settings_general']['addressbook_name_format'] = array(
     '#type' => 'select',
     '#title' => t('Name format '),
     '#default_value' => variable_get('addressbook_name_format',1),
     '#options' => array( 0 => t('middle last, first'), 1 => t('first middle last') ),
     '#description' => t('Set the name format which will be used in the general addressbook list page.'));

  $form['settings_general']['addressbook_show_sort_bar'] = array(
     '#type' => 'select',
     '#title' => t('Enable sort bar'),
     '#default_value' => variable_get('addressbook_show_sort_bar',1),
     '#options' => array( 0 => t('No'), 1 => t('Yes') ),
     '#description' => t('Enable / disable sort bar in general addressbook list page.'));

  $form['settings_general']['addressbook_roles'] = array(
     '#type' => 'textarea',
     '#title' => t('Roles'),
     '#default_value' => variable_get('addressbook_roles', ''),
     '#rows' => 1,
     '#description' => t("Enter the roles which a person can have (Seperate items with commas (,). No spaces allowed).") );

  $form['settings_general']['addressbook_country'] = array(
     '#type' => 'textfield',
     '#title' => t('Country'),
     '#default_value' => variable_get('addressbook_country', t('Nederland')),
     '#description' => t("Specify default country for new address items."),
     '#maxlength' => '50',
     '#size' => '50');

  $form['settings_general']['addressbook_show_thumbnails'] = array(
     '#type' => 'select',
     '#title' => t('Show thumbnails pictures in list views'),
     '#default_value' => variable_get('addressbook_show_thumbnails',0),
     '#options' => array( 0 => t('No'), 1 => t('Yes') ),
     '#description' => t('Enable / disable thumbnail pictures in family list and family member list.'));

  $form['settings_general']['addressbook_email_manitory'] = array(
     '#type' => 'select',
     '#title' => t('Email field manitory'),
     '#default_value' => variable_get('addressbook_email_manitory',1),
     '#options' => array( 0 => t('No'), 1 => t('Yes') ),
     '#description' => t('Enable / disable email field as mandatory field.'));

  $form['settings_general']['addressbook_wiki_edit_mode'] = array(
     '#type' => 'select',
     '#title' => t('Wiki edit mode'),
     '#default_value' => variable_get('addressbook_wiki_edit_mode',0),
     '#options' => array( 0 => t('Disable'), 1 => t('Enable') ),
     '#description' => t('Enable (anyone can modify existing addresses), Disable (only owner can modify created addresses).'));



  $form['map24'] = array('#type' => 'fieldset', '#title' => t('Map settings'));

  $form['map24']['addressbook_map_link'] = array(
     '#type' => 'select',
     '#title' => t('Activate map link'),
     '#default_value' => variable_get('addressbook_map_link',0),
     '#options' => array( 0 => t('No'), 1 => t('Yes') ),
     '#description' => t('Enable / Disable Activate www.map24.com fast link.'));

  $form['map24']['addressbook_map_key'] = array(
     '#type' => 'textfield',
     '#title' => t('Free www.map24.com access key'),
     '#default_value' => variable_get('addressbook_map_key', ''),
     '#description' => t("Enter access key (Visit http://www.map24.com to obtain a free key)"),
     '#maxlength' => '50',
     '#size' => '50');



  $form['birthday'] = array('#type' => 'fieldset', '#title' => t('Birthday notification settings'));

  $form['birthday']['addressbook_birthday_notification'] = array(
     '#type' => 'select',
     '#title' => t('Birthday email notification'),
     '#default_value' => variable_get('addressbook_birthday_notification',0),
     '#options' => array( 0 => t('No'), 1 => t('Yes') ),
     '#description' => t('Enable / disable email birthday notification.'));

  $form['birthday']['addressbook_birthday_subject'] = array(
     '#type' => 'textfield',
     '#title' => t('Subject of birtday e-mail'),
     '#default_value' => variable_get('addressbook_birthday_subject','Happy birthday %username from %site_name'),
     '#maxlength' => 180,
     '#description' => t('Customize the subject of your birthday e-mail, which is sent to members upon their birthday.') .' '. t('Available variables are:') .' %username, %site_name');

  $form['birthday']['addressbook_birthday_body'] = array(
     '#type' => 'textarea',
     '#title' => t('Body of birthday e-mail'),
     '#default_value' => variable_get('addressbook_birthday_body',"Dear %username,\r\n\r\nCongratulation with your %user_age ste birthday.\r\nHave a nice day!\r\n"),
     '#rows' => 15,
     '#description' => t('Customize the body of the birthday e-mail, which is sent to members upon their birthday.') .' '. t('Available variables are:') .' %username, %user_age, %site_name');

  return system_settings_form($form);

}

// ##################################################################################
// Cron
// ##################################################################################

/**
  * Find all family members which are celebrating their birthday to day and send them an email.
  * @return emails
  */
function addressbook_cron() {

  // If birthday notification is enabled check all family members.
  if ( variable_get('addressbook_birthday_notification',0)==1 ) {

    // Send the birthday notication only once in any given day (crontab may run more frequently)
    $current_day=date('-m-d');
    $current_time=date('H');

    if ($current_time==0) {
      watchdog('cron', t('Addressbook birthday cron'));

      // Fetch all members with are celebrating there birtday
      $query='SELECT first_name, middle_name, last_name, email, birth_day FROM {addressbook_member} WHERE birth_day LIKE "%'.$current_day.'"';
      $queryResult = db_query($query);
      while ($data = db_fetch_object($queryResult)) {
        $username=view_name($data->first_name,$data->middle_name,$data->last_name,true);

        $email = $data->email;
        $site_name = variable_get('site_name', 'Drupal');

        // Calculate member age
        list($year, $month, $day) = split('[/.-]', $data->birth_day);
        $user_age  = date('Y')-$year;

        // if family member have a email address send a email
        if (($email!='') && ($user_age<100)) {
          $from=$site_name.'<'.variable_get('site_mail', ini_get('sendmail_from')).'>';

          $subject=variable_get('addressbook_birthday_subject','Happy birthday %username from %site_name');
          $subject=str_replace("%username", $username, $subject);
          $subject=str_replace("%site_name", $site_name, $subject);

          $body=variable_get('addressbook_birthday_body',"Dear %username,\r\n\r\nCongratulation with your %user_age ste birthday.\r\nHave a nice day!\r\n");
          $body=str_replace("%username", $username, $body);
          $body=str_replace("%user_age", $user_age, $body);
          $body=str_replace("%site_name", $site_name, $body);

          if (drupal_mail('Addressbook', 'send', $email, user_preferred_language($user), array('subject'=>$subject,'body'=>$body))) 
          {           
            watchdog('cron', t('Sent birthday email to ').$email);
          }
          else 
          {
            watchdog('cron', t('Unable to email to ').$email);
          }
        }
      }
    }
  }
}

// ##################################################################################
// Block
// ##################################################################################

/**
  * Find all family members which are celebrating their birthday today and make a block of it.
  * @return emails
  */
function addressbook_block($op='list', $delta=0) {

  // listing of blocks, such as on the admin/block page
  if ($op == "list") {

    $block[0]["info"] = t('Birthday today');
    return $block;

  } else if ($op == 'view') {

    // our block content
    // content variable that will be returned for display
    $block_content = '';

    if (user_access('view addressbook')) {
      $current_day=date('-m-d');
      $current_time=date('H');

      $query='SELECT mid, first_name, middle_name, last_name, email, birth_day FROM {addressbook_member} WHERE birth_day LIKE "%'.$current_day.'"';
      $queryResult = db_query($query);
      while ($data = db_fetch_object($queryResult)) {

        // Calculate member age
        list($year, $month, $day) = split('[/.-]', $data->birth_day);
        $user_age  = date('Y')-$year;

        $name=view_name($data->first_name,$data->middle_name,$data->last_name,true,false,true);
        $block_content .= l( $name.' ['.$user_age.'] ',URL_MEMBER_VIEW.'/'.$data->mid) . '<br />';
      }
    }

    // check to see if there was any content before setting up the block
    if ($block_content == '') {
        // no content from a week ago, return nothing.
        return;
    }
    // set up the block
    $block['subject'] = 'Birthday today';
    $block['content'] = $block_content;
    return $block;
  }
}

// ##################################################################################
// The end
// ##################################################################################